import PDFDocument from 'pdfkit';
import { IContract } from './contract.model';
import { IContractVersion } from '../contract-versions/version.model';

export function renderContractPdf(contract: IContract, version: IContractVersion | null): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 56 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).font('Helvetica-Bold').text(contract.title, { align: 'center' });
    doc.moveDown(0.25);
    doc.fontSize(10).font('Helvetica').fillColor('#555555').text(`Contract Number: ${contract.contractNumber}`, {
      align: 'center',
    });
    doc.fillColor('#000000');
    doc.moveDown(1);

    doc.fontSize(12).font('Helvetica-Bold').text('Contract Details');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica');
    const details: Array<[string, string]> = [
      ['Contract Type', String(contract.contractType)],
      ['Status', String(contract.status)],
      ['Effective Date', formatDate(contract.effectiveDate)],
      ['Expiry Date', formatDate(contract.expiryDate)],
      ['Governing Law', contract.governingLawCountry ?? '—'],
      ['Contract Value', contract.contractValue != null ? `${contract.contractValue} ${contract.currency ?? ''}`.trim() : '—'],
      ['Confidentiality', contract.confidentialityLevel],
    ];
    for (const [label, value] of details) {
      doc.font('Helvetica-Bold').text(`${label}: `, { continued: true }).font('Helvetica').text(value);
    }
    doc.moveDown(1);

    doc.fontSize(12).font('Helvetica-Bold').text('Parties');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica');
    if (contract.parties.length === 0) {
      doc.text('No parties recorded.');
    } else {
      for (const party of contract.parties) {
        doc.text(`• ${party.name} — ${party.role} (${party.partyType})`);
      }
    }
    doc.moveDown(1);

    if (version) {
      doc.fontSize(12).font('Helvetica-Bold').text(`Contract Body (Version ${version.versionNumber})`);
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica');
      const entries = Object.entries(version.content ?? {});
      if (entries.length === 0) {
        doc.text('No content recorded for this version.');
      } else {
        for (const [key, value] of entries) {
          doc.font('Helvetica-Bold').text(`${key}: `, { continued: true }).font('Helvetica').text(renderValue(value));
        }
      }
      doc.moveDown(1);
      if (version.changeSummary) {
        doc.fontSize(9).fillColor('#555555').text(`Change summary: ${version.changeSummary}`);
        doc.fillColor('#000000');
      }
    }

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#777777').text(
      'This document was generated by the CLM Platform for the purpose of collecting signatures. ' +
        'Signature confirmation and the full audit trail are recorded in the platform once the ' +
        'e-signature provider reports completion.',
      { align: 'left' }
    );

    doc.end();
  });
}

function formatDate(date: Date | null): string {
  if (!date) return '—';
  return new Date(date).toISOString().slice(0, 10);
}

function renderValue(value: unknown): string {
  if (value === null || value === undefined) return '—';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}
